services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-eleicoes
    restart: always
    env_file:
      - .env
    volumes:
      - static-data:/app/static/
      - shared_sockets:/app/uwsgi/
    command: >
      sh -c "python3 manage.py collectstatic --no-input &&
             python3 manage.py migrate &&
             python3 manage.py create_admin_user &&
             uwsgi --ini uwsgi.ini"
    networks:
      - sistema-eleicoes-network
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static-data:/app/static/
      - shared_sockets:/run/uwsgi/
      - ./uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sistema-eleicoes-network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -sf localhost/login/ || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 5s


volumes:
  static-data:
    driver: local	
  shared_sockets:
    driver: local

networks:
  sistema-eleicoes-network:
    driver: bridge