# Generated by Django 5.1.6 on 2025-04-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='teams_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('2DS', '2º Desenvolvimento de Sistemas'), ('3DS', '3º Desenvolvimento de Sistemas'), ('1A', '1º Administração'), ('2A', '2º Administração'), ('3A', '3º Administração'), ('1E', '1º Enfermagem'), ('2E', '2º Enfermagem'), ('3E', '3º Enfermagem'), ('1I', '1º Informática'), ('3I', '3º Informática'), ('1L', '1º Logística'), ('2L', '2º Logística')], max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='votes.team')),
            ],
        ),
    ]
